[package]
name = "lumos"
version = "0.1.0"
authors = ["Florian Büstgens <florian.buestgens@efficient-dev.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
bootloader = "0.9.8"
spin = "0.5.2"
volatile = "0.2.6"
x86_64 = "0.14.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"