[package]
name = "falcon"
version = "0.1.0"
authors = ["Florian Büstgens <florian.buestgens@efficient-dev.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"