[workspace]
resolver = "2"
members = [
    "kernel",
    "domains/apic",
    "domains/gdt",
    "domains/cores",
    "domains/uio",
    "domains/exception",
    "domains/idt",
    "domains/security",
    "libs/kstructs",
    "libs/khadron"
]
