[package]
name = "idt"
version = "0.1.0"
authors = ["Florian Marrero Liestmann <f.m.liestmann@fx-ttr.de>"]
edition = "2021"

[dependencies]
lazy_static = "1.4.0"

[dependencies.x86_64]
path = "../../libs/x86_64"

[dependencies.uio]
path = "../uio"
