[package]
name = "security"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.2"
bitflags = "2.4.1"

[dependencies.x86_64]
path = "../../libs/x86_64"
