[package]
name = "security"
version = "0.1.0"
authors = ["Florian Marrero Liestmann <f.m.liestmann@fx-ttr.de>"]
edition = "2021"

[dependencies]
bit_field = "0.10.2"
bitflags = "2.6.0"

[dependencies.x86_64]
path = "../../libs/x86_64"
